vim.keymap.set("n", "<leader>mh", require("harpoon.mark").add_file)
vim.keymap.set("n", "<leader>mm", require("harpoon.ui").toggle_quick_menu)
vim.keymap.set("n", "<A-h>", function()
	require("harpoon.ui").nav_file(1)
end)
vim.keymap.set("n", "<A-t>", function()
	require("harpoon.ui").nav_file(2)
end)
vim.keymap.set("n", "<A-n>", function()
	require("harpoon.ui").nav_file(3)
end)
vim.keymap.set("n", "<A-s>", function()
	require("harpoon.ui").nav_file(4)
end)
vim.keymap.set("n", "<A-j>", require("harpoon.ui").nav_next)
vim.keymap.set("n", "<A-k>", require("harpoon.ui").nav_prev)
