require("config.packer")
require("config.globals")
require("config.autocmds")
require("config.keymaps")
require("config.telescope")
require("config.nvimtree")
require("config.lsp")
-- require("config.colors").set()
